# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 684489a96888fddf77d900ca8548dfac5d90294e11d47dd5b6cbf95a725fb94d5a0722b9b29bf7b3ffd109ada177dfce65539b8bb666263763e31da9dd71b6fb

test:
  secret_key_base: 71755256d07a422397e7c563b0011cdf8ea78c34e0ff92a0fb475999cb7bf0ffd8def4925429d3eb0a9176af8b513ecbf78f9c74af91c665d2655bea74e3dda9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
